---
- name: install ceph for debian
  apt:
    name: "ceph"
    update_cache: no
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
    default_release: "{{ ceph_stable_release_uca | default(ansible_distribution_release) }}{{ '-backports' if ceph_origin == 'distro' and ceph_use_distro_backports else ''}}"

- name: install ceph-common for debian
  apt:
    name: ceph-common
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
    default_release: "{{ ceph_stable_release_uca | default(ansible_distribution_release) }}{{ '-backports' if ceph_origin == 'distro' and ceph_use_distro_backports else ''}}"

- name: install ceph-test for debian
  apt:
    name: ceph-test
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
    default_release: "{{ ceph_stable_release_uca | default(ansible_distribution_release) }}{{ '-backports' if ceph_origin == 'distro' and ceph_use_distro_backports else ''}}"
  when:
    - ceph_test

- name: install rados gateway for debian
  apt:
    name: radosgw
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
    update_cache: yes
  when:
    - rgw_group_name in group_names

- name: install ceph mds for debian
  apt:
    name: ceph-mds
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
    default_release: "{{ ceph_stable_release_uca | default(ansible_distribution_release) }}{{ '-backports' if ceph_origin == 'distro' and ceph_use_distro_backports else ''}}"
  when:
    - mds_group_name in group_names

- name: install jemalloc for debian
  apt:
    name: libjemalloc1
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
    update_cache: yes
  when:
    - nfs_group_name in group_names

- name: install nfs gateway for debian
  apt:
    name: nfs-ganesha-fsal
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
    update_cache: yes
  when:
    - nfs_group_name in group_names

- name: install ceph mgr for debian
  apt:
    name: ceph-mgr
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
    default_release: "{{ ceph_stable_release_uca | default(ansible_distribution_release) }}{{ '-backports' if ceph_origin == 'distro' and ceph_use_distro_backports else ''}}"
  when:
    - mgr_group_name in group_names
    - ceph_release_num.{{ ceph_release }} > ceph_release_num.jewel
